services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    container_name: codevn-web
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - ./public/uploads:/app/public/uploads
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    container_name: codevn-api
    ports:
      - '3001:3001'
    volumes:
      - ./public/uploads:/app/public/uploads
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001/api/health']
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    container_name: codevn-migrate
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    command: ['pnpm', 'db:push']
    restart: 'no'

  postgres:
    image: postgres:17
    container_name: codevn-postgres
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    command: >
      postgres
      -c max_connections=100
      -c shared_buffers=1536MB
      -c effective_cache_size=4GB
      -c maintenance_work_mem=128MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: codevn-pgadmin
    env_file: .env
    ports:
      - '5433:80'
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis:
    image: redis:8-alpine
    container_name: codevn-redis
    env_file: .env
    ports:
      - '6379:6379'
    command: >
      redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    restart: unless-stopped

  nginx:
    image: nginx:1.29-alpine
    container_name: codevn-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/app/public:ro
    depends_on:
      - web
      - api
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/status']
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:
